updated marketdataroutes router and updated api call.
Kay-code-1/investor-portfolio pull request #31
Opened 2021-09-18 20:44 UTC by kjphelps90

2021-09-18 20:51 UTC, Kay-code-1 requested changes

2021-09-18 20:51 UTC, Kay-code-1 commented on public/js/home.js
>      const apiKey = await apiKeyResponse.json();
change the variable name to a suitable name

2021-09-18 20:51 UTC, Kay-code-1 commented on controllers/api/marketDataRoutes.js
> +    res.status(200).json(url);
Do not return the url, instead return response of market stats.

2021-09-18 20:59 UTC, Esun94 approved these changes

2021-09-19 00:44 UTC, Kay-code-1 approved these changes

2021-09-19 00:44 UTC, merged